### ISSUE TITLE
[Meta] Checklist for Deprecating Hadoop 1.x Support and the Elasticsearch on YARN Project

### ISSUE THREAD

**Issue by acchen97** [elastic/elasticsearch-hadoop#1001]
Checklist for upcoming deprecations in 5.5. Addresses https://github.com/elastic/elasticsearch-hadoop/issues/1000.

### Deprecating Hadoop 1.x Support
- [x] Support notice
- [x] Deprecation blog post
- [x] [Docs](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/requirements.html#requirements-hadoop) updates
  - [x] Deprecation note
  - [x] Remove distribution test list

### Deprecating Elasticsearch on YARN
- [x] Deprecation note in [docs](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/es-yarn.html)
- [x] Deprecation note in [Github repo](https://github.com/elastic/elasticsearch-hadoop/tree/master/yarn)

**Comment by jbaiera** [comment]
Closing this as the deprecations have been broadcast through all channels
