### ISSUE TITLE
ES-Hadoop 6.4 Release

### ISSUE THREAD

**Issue by acchen97** [elastic/elasticsearch-hadoop#1110]
Tracking high level features for the 6.4 release:
- [x] Secure storage for sensitive credentials - https://github.com/elastic/elasticsearch-hadoop/pull/1174
- Error Handlers - beta-to-GA
  - [x] Expose handlers for inputs and serialization errors - https://github.com/elastic/elasticsearch-hadoop/pull/1149
  - [x] Elasticsearch dead letter handler - https://github.com/elastic/elasticsearch-hadoop/pull/1167

**Comment by acchen97** [comment]
Good work @jbaiera, closing...
