### ISSUE TITLE
ES-Hadoop 6.5 Release

### ISSUE THREAD

**Issue by acchen97** [elastic/elasticsearch-hadoop#1176]
Tracking high level features for the 6.5 release:
- [x] ILM integration/Write alias improvements (#1197)
- [ ] ~~Elasticsearch Kerberos realm integration~~ - https://github.com/elastic/elasticsearch-hadoop/issues/1175
- [ ] Deprecation notices for 7.0

**Comment by jbaiera** [comment]
6.5 has been released for some time now. Closing.
