### ISSUE TITLE
ES-Hadoop 5.3 release

### ISSUE THREAD

**Issue by acchen97** [elastic/elasticsearch-hadoop#916]
Tracking high-level features for the 5.3 release:
- [x] Add support for Spark 2.1 - https://github.com/elastic/elasticsearch-hadoop/issues/915
- [x] Unicode support in REST client - https://github.com/elastic/elasticsearch-hadoop/issues/857
- [x] HTTP header customization - https://github.com/elastic/elasticsearch-hadoop/issues/927
