### ISSUE TITLE
ES-Hadoop 6.0 release

### ISSUE THREAD

**Issue by acchen97** [elastic/elasticsearch-hadoop#966]
Tracking high-level features for the 6.0 release:
- [x] Spark 2.2 support - #1013 
- [x] Spark Structured Streaming support for Spark 2.2.x - https://github.com/elastic/elasticsearch-hadoop/issues/818
- [x] Support for Join Field - #1012 
- [ ] Multi-axial testing for Spark
- [ ] Better document security privileges

**Comment by acchen97** [comment]
@jbaiera when you have the chance, can you create an issue outlining the work for Structured Streaming?

**Comment by jbaiera** [comment]
@acchen97 There's an issue already open at #818

**Comment by dmarkhas** [comment]
Will the 6.x branch support ElasticSearch 5.x, or will it only be compatible with ElasticSearch 6.x?

**Comment by acchen97** [comment]
@dmarkhas ES-Hadoop 6.0 will be compatible with Elasticsearch 5.6. We support the last minor of the previous major version of Elasticsearch.

**Comment by jbaiera** [comment]
6.0 has set sail. Closing.
