### ISSUE TITLE
Scala Compiler Warnings

### ISSUE THREAD

**Issue by jbaiera** [elastic/elasticsearch-hadoop#969]
We should probably not tolerate compiler warnings in Scala any longer, especially since there's only a handful that I can see in the project (currently 13 in each spark project 1.6 & 2.0). This is a meta ticket for fixing compiler warnings in Scala, and after this ticket is completed, the compiler should be configured with '-Xfatal-warnings' to ensure no more compiler warnings are committed going forward (as they will fail the build).

- [x] #970 Fix discarded return value Scala compiler warnings
- [x] #971 Fix unchecked type Scala compiler warnings.
- [x] #972 Fix dead code Scala compiler warnings
- [x] #973 Fix implicit conversion method Scala compiler warnings
- [x] #974 Enable Fatal Warnings on Scala Compiler

**Comment by takezoe** [comment]
I can work for them.

**Comment by jbaiera** [comment]
Closing this issue out as all sub-items have been closed out or merged.
