### ISSUE TITLE
Enable Fatal Warnings on Scala Compiler

### ISSUE THREAD

**Issue by jbaiera** [elastic/elasticsearch-hadoop#974]
Subtask of #969 

We should be catching and fixing common warnings in Scala that are reported by the compiler. Many of these are easy to miss and can evolve into bugs down the line if they aren't caught and fixed early. Enabling `-Xfatal-warnings` on the Scala compiler will fail builds if there are easily fixable Scala warnings, thus forcing developer(s) to handle them.

This depends on current warnings to be smashed out:
- [x] #970 Fix discarded return value Scala compiler warnings
- [x] #971 Fix unchecked type Scala compiler warnings.
- [x] #972 Fix dead code Scala compiler warnings
- [x] #973 Fix implicit conversion method Scala compiler warnings
